spring:
  application:
    name: backend-test-deploy
    
  profiles:
    active: prod  # Perfil por defecto

---
# Configuración para el perfil 'default'
spring:
  config:
    activate:
      on-profile: default
 
springdoc:     
  swagger-ui:
    path: /swagger-ui-custom.html

---
# Configuración para el perfil 'dev'
spring:
  config:
    activate:
      on-profile: dev
 
springdoc:     
  swagger-ui:
    path: /swagger-ui-custom.html

---
# Configuración para el perfil 'prod'
spring:
  config:
    activate:
      on-profile: prod

server:
  forward-headers-strategy: framework  # Habilita detección de protocolo HTTPS en producción
  port: 5000 #Este numero de puerto es para desplegarlo en AWS Elastic Beanstalk, ya que por defecto utiliza este puerto porque trabaja con NGnix

springdoc:    
  swagger-ui:
    path: /swagger-ui-custom.html