name: Build Backend Test and Push Docker Image #Nombre del workflow

on:
  push: #este workflow se activara cada vez que yo haga un push al repositorio
    branches:
      - main  #es la rama que tengo mi repositorio

jobs: #conjunto de tareas
  build:
    runs-on: ubuntu-latest #el SO necesario para poder compilar el proyecto

    steps:
      - name: Check out the code
        uses: actions/checkout@v3 #esto descarga el codigo del repositorio en el entorno de ejecución, para que los siguientes pasos tengan acceso al codigo fuente

      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17' #La version de java que estoy usando
          distribution: 'temurin' #especifica la distribucion de JDK

      - name: Dando permisos de ejecucion para Maven Wrapper
        run: chmod +x ./mvnw
        
      - name: Build JAR
        run: ./mvnw clean package -DskipTests #Aca estoy construyendo el jar de mi proyecto

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        #run: docker build -t luisorihuela92/back-test:${{ github.sha }} . #Aca construye la imagen y lo tagea
        run: docker build -t luisorihuela92/back-test:latest . #de esta manera manejamos los tags y las versiones

      - name: Push Docker image to Docker Hub
        #run: docker push luisorihuela92/back-test:${{ github.sha }} # Y por último lo sube a Docker Hub
        run: docker push luisorihuela92/back-test:latest
